<?php

use App\Models\CustomerEnrichment;

uses(\Illuminate\Foundation\Testing\RefreshDatabase::class);

describe('CustomerEnrichment Model', function () {
    describe('company size calculation', function () {
        it('returns micro for less than 10 employees', function () {
            expect(CustomerEnrichment::calculateCompanySize(1))->toBe('micro');
            expect(CustomerEnrichment::calculateCompanySize(5))->toBe('micro');
            expect(CustomerEnrichment::calculateCompanySize(9))->toBe('micro');
        });

        it('returns small for 10-49 employees', function () {
            expect(CustomerEnrichment::calculateCompanySize(10))->toBe('small');
            expect(CustomerEnrichment::calculateCompanySize(25))->toBe('small');
            expect(CustomerEnrichment::calculateCompanySize(49))->toBe('small');
        });

        it('returns medium for 50-249 employees', function () {
            expect(CustomerEnrichment::calculateCompanySize(50))->toBe('medium');
            expect(CustomerEnrichment::calculateCompanySize(100))->toBe('medium');
            expect(CustomerEnrichment::calculateCompanySize(249))->toBe('medium');
        });

        it('returns large for 250+ employees', function () {
            expect(CustomerEnrichment::calculateCompanySize(250))->toBe('large');
            expect(CustomerEnrichment::calculateCompanySize(500))->toBe('large');
            expect(CustomerEnrichment::calculateCompanySize(1000))->toBe('large');
        });

        it('returns null for null input', function () {
            expect(CustomerEnrichment::calculateCompanySize(null))->toBeNull();
        });
    });

    describe('TEAOR to sector mapping', function () {
        it('maps agriculture codes correctly', function () {
            expect(CustomerEnrichment::mapTeaorToSector('0111'))->toBe('Agriculture');
            expect(CustomerEnrichment::mapTeaorToSector('02'))->toBe('Agriculture');
            expect(CustomerEnrichment::mapTeaorToSector('0321'))->toBe('Agriculture');
        });

        it('maps retail and wholesale codes correctly', function () {
            expect(CustomerEnrichment::mapTeaorToSector('4520'))->toBe('Retail & Wholesale');
            expect(CustomerEnrichment::mapTeaorToSector('4711'))->toBe('Retail & Wholesale');
            expect(CustomerEnrichment::mapTeaorToSector('4799'))->toBe('Retail & Wholesale');
        });

        it('maps transportation codes correctly', function () {
            expect(CustomerEnrichment::mapTeaorToSector('4941'))->toBe('Transportation & Logistics');
            expect(CustomerEnrichment::mapTeaorToSector('5110'))->toBe('Transportation & Logistics');
            expect(CustomerEnrichment::mapTeaorToSector('5320'))->toBe('Transportation & Logistics');
        });

        it('maps IT and media codes correctly', function () {
            expect(CustomerEnrichment::mapTeaorToSector('6201'))->toBe('IT & Media');
            expect(CustomerEnrichment::mapTeaorToSector('5811'))->toBe('IT & Media');
            expect(CustomerEnrichment::mapTeaorToSector('6311'))->toBe('IT & Media');
        });

        it('maps manufacturing codes correctly', function () {
            expect(CustomerEnrichment::mapTeaorToSector('1011'))->toBe('Manufacturing');
            expect(CustomerEnrichment::mapTeaorToSector('2599'))->toBe('Manufacturing');
        });

        it('returns Other for unknown codes', function () {
            expect(CustomerEnrichment::mapTeaorToSector('9999'))->toBe('Other');
            expect(CustomerEnrichment::mapTeaorToSector('0000'))->toBe('Other');
        });
    });

    describe('scopes', function () {
        beforeEach(function () {
            CustomerEnrichment::factory()->enriched()->count(3)->create();
            CustomerEnrichment::factory()->notEnriched()->count(2)->create();
            CustomerEnrichment::factory()->failed()->count(1)->create();
        });

        it('filters enriched customers', function () {
            expect(CustomerEnrichment::enriched()->count())->toBe(3);
        });

        it('filters not enriched customers', function () {
            expect(CustomerEnrichment::notEnriched()->count())->toBe(2);
        });

        it('filters failed enrichments', function () {
            expect(CustomerEnrichment::failed()->count())->toBe(1);
        });

        it('filters by industry sector', function () {
            // Use a unique sector that won't be generated by factory
            CustomerEnrichment::factory()->enriched()->create(['industry_sector' => 'Public Administration']);

            expect(CustomerEnrichment::byIndustry('Public Administration')->count())->toBe(1);
        });

        it('filters by company size', function () {
            // Count existing before adding
            $existingMicro = CustomerEnrichment::bySize('micro')->count();
            $existingLarge = CustomerEnrichment::bySize('large')->count();

            CustomerEnrichment::factory()->micro()->enriched()->create();
            CustomerEnrichment::factory()->large()->enriched()->create();

            expect(CustomerEnrichment::bySize('micro')->count())->toBe($existingMicro + 1);
            expect(CustomerEnrichment::bySize('large')->count())->toBe($existingLarge + 1);
        });

        it('filters by city', function () {
            CustomerEnrichment::factory()->enriched()->create(['city' => 'Budapest']);

            expect(CustomerEnrichment::byCity('Budapest')->count())->toBe(1);
        });
    });

    describe('marking methods', function () {
        it('can mark as enriched', function () {
            $enrichment = CustomerEnrichment::factory()->notEnriched()->create();

            $enrichment->markAsEnriched('test', ['key' => 'value']);

            expect($enrichment->fresh())
                ->enrichment_source->toBe('test')
                ->enrichment_failed->toBeFalse()
                ->enriched_at->not->toBeNull();
        });

        it('can mark as failed', function () {
            $enrichment = CustomerEnrichment::factory()->enriched()->create();

            $enrichment->markAsFailed('Test error message');

            expect($enrichment->fresh())
                ->enrichment_failed->toBeTrue()
                ->enrichment_error->toBe('Test error message');
        });
    });
});
